steps:
  - label: 'Code Coverage (experimental)'
    commands:
    - RUSTC_WRAPPER="" RUSTFLAGS="-Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off" cargo cov test --lib
    - zip -0 ccov.zip *.gc*
    - grcov ccov.zip -s . -t lcov > lcov0.info
    - lcov --remove lcov0.info "*rustc*" -o lcov1.info
    - lcov --remove lcov1.info "*registry*" -o lcov.info
    - bash <(curl -s https://codecov.io/bash) -f lcov.info || echo "Codecov did not collect coverage reports"
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/osrank-build@sha256:00e4c02a7391457031c2f3d3a548e92aa44fd2341de08918968040fe9f2793eb"
    agents:
      platform: "linux"
      production: "true"
