steps:
  - label: 'Code Coverage (experimental)'
    command: |
        RUSTC_WRAPPER="" RUSTFLAGS="-Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off" cargo cov test --all;
        zip -0 ccov.zip `find . \( -name "osrank*.gc*" \) -print`;
        grcov ccov.zip -s . -t lcov > lcov0.info;
        lcov --remove lcov0.info "*rustc*" -o lcov1.info;
        lcov --remove lcov1.info "*registry*" -o lcov.info;
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/osrank-build@sha256:630f3d148d1144e79157bee1685ff3130b6cd620cb77300916c691fcbe29e696"
    agents:
      docker: "true"
