steps:
  - label: 'Benchmarks'
    command: |
        CRITERION_DEBUG=1 cargo bench -- --measurement-time 50 --sample-size 10 dev
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/osrank-build@sha256:d9cb3dce4f4af6d9a7db1669617638fbd5719498ecdf8246d99a4e724b65139b"
    agents:
      docker: "true"
    artifact_paths:
      - "target/criterion/report/*"
