steps:
  - label: "Tests"
    command: 'cargo test --features build-binary --all'
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/osrank-build@sha256:630f3d148d1144e79157bee1685ff3130b6cd620cb77300916c691fcbe29e696"
    agents:
      docker: "true"

  - label: "Compile benchmarks (no-run)"
    command: 'cargo bench --no-run'
    env:
      DOCKER_IMAGE: "gcr.io/opensourcecoin/osrank-build@sha256:630f3d148d1144e79157bee1685ff3130b6cd620cb77300916c691fcbe29e696"
    agents:
      docker: "true"
